// Generated by CoffeeScript 1.6.3
(function() {
  var ACTION_THRESHOLDS, SHIELD_THRESHOLDS;

  ACTION_THRESHOLDS = [3, 15, 35, 63, 99];

  SHIELD_THRESHOLDS = [8, 24, 48, 80];

  $(function() {
    var fame, rep;
    rep = parseInt(localStorage.mage_knight_current_reputation || 0);
    $(".currentReputation").text(rep);
    fame = parseInt(localStorage.mage_knight_current_fame || 0);
    $(".currentFame").text(fame);
    $(".reset").click(function() {
      var confirmed;
      confirmed = window.confirm("Really reset? You can't undo this.");
      if (!confirmed) {
        return;
      }
      localStorage.mage_knight_current_reputation = 0;
      localStorage.mage_knight_current_fame = 0;
      $(".currentReputation").text(0);
      return $(".currentFame").text(0);
    });
    $(".incrCurrentReputation").mousedown(function() {
      var newRep;
      newRep = parseInt($(".currentReputation").text(), 10) + 1;
      localStorage.mage_knight_current_reputation = newRep;
      return $(".currentReputation").text(newRep);
    });
    $(".decrCurrentReputation").mousedown(function() {
      var newRep;
      newRep = parseInt($(".currentReputation").text(), 10) - 1;
      localStorage.mage_knight_current_reputation = newRep;
      return $(".currentReputation").text(newRep);
    });
    $(".addFameButton").click(function() {
      $(".view").hide();
      return $(".editView").show();
    });
    $(".incrNewFame").mousedown(function() {
      return $(".newFame").text(parseInt($(".newFame").text(), 10) + 1);
    });
    $(".decrNewFame").mousedown(function() {
      return $(".newFame").text(parseInt($(".newFame").text(), 10) - 1);
    });
    $(".doneNewFame").click(function() {
      var action_bumps, addedVal, level_bumps, message, newFame, oldFame, step, total_shields, total_skills, _i;
      addedVal = parseInt($(".newFame").text(), 10);
      oldFame = parseInt($(".currentFame").text(), 10);
      newFame = addedVal + oldFame;
      localStorage.mage_knight_current_fame = newFame;
      action_bumps = 0;
      level_bumps = 0;
      total_shields = 1;
      total_skills = 0;
      for (step = _i = oldFame; oldFame <= newFame ? _i < newFame : _i > newFame; step = oldFame <= newFame ? ++_i : --_i) {
        if (_(ACTION_THRESHOLDS).contains(step)) {
          action_bumps += 1;
          total_skills = ACTION_THRESHOLDS.indexOf(step) + 1;
        }
        if (_(SHIELD_THRESHOLDS).contains(step)) {
          level_bumps += 1;
          total_shields = SHIELD_THRESHOLDS.indexOf(step) + 2;
        }
      }
      message = "Done. Your Fame level is now " + newFame;
      if (action_bumps >= 1) {
        message = "Awesome! Now that your Fame level is " + newFame + ", you may now choose " + action_bumps + " new Advanced Action card and " + action_bumps + " new Character Skill.<br/><br/>You should now have a total of " + total_skills + " Character Skills.";
      }
      if (level_bumps >= 1) {
        message = "Great news! Now that your Fame has increased to " + newFame + ", you may now take " + level_bumps + " shield from your stack and flip it over.<br /><br />You should now have a total of " + total_shields + " available shields.";
      }
      $(".newFame").text(0);
      $(".currentFame").text(newFame);
      $(".view").hide();
      $(".effectView").show();
      return $(".effect").html(message);
    });
    return $(".button.ok").click(function() {
      $(".view").hide();
      return $(".mainDisplay").show();
    });
  });

}).call(this);
