// Generated by CoffeeScript 1.6.3
(function() {
  var ACTION_THRESHOLDS, SHIELD_THRESHOLDS, plur;

  ACTION_THRESHOLDS = [3, 15, 35, 63, 99];

  SHIELD_THRESHOLDS = [8, 24, 48, 80];

  plur = function(num, word) {
    if (num === 1) {
      return word;
    } else {
      return "" + word + "s";
    }
  };

  $(function() {
    var fame, rep;
    rep = parseInt(localStorage.mage_knight_current_reputation || 0);
    $(".currentReputation").text(rep);
    fame = parseInt(localStorage.mage_knight_current_fame || 0);
    $(".currentFame").text(fame);
    $(".reset").click(function() {
      var confirmed;
      confirmed = window.confirm("Really reset? You can't undo this.");
      if (!confirmed) {
        return;
      }
      localStorage.mage_knight_current_reputation = 0;
      localStorage.mage_knight_current_fame = 0;
      $(".currentReputation").text(0);
      return $(".currentFame").text(0);
    });
    $(".incrCurrentReputation").mousedown(function() {
      var newRep;
      newRep = parseInt($(".currentReputation").text(), 10) + 1;
      localStorage.mage_knight_current_reputation = newRep;
      return $(".currentReputation").text(newRep);
    });
    $(".decrCurrentReputation").mousedown(function() {
      var newRep;
      newRep = parseInt($(".currentReputation").text(), 10) - 1;
      localStorage.mage_knight_current_reputation = newRep;
      return $(".currentReputation").text(newRep);
    });
    $(".addFameButton").click(function() {
      $(".view").hide();
      return $(".editView").show();
    });
    $(".incrNewFame").mousedown(function() {
      return $(".newFame").text(parseInt($(".newFame").text(), 10) + 1);
    });
    $(".decrNewFame").mousedown(function() {
      return $(".newFame").text(parseInt($(".newFame").text(), 10) - 1);
    });
    $(".doneNewFame").click(function() {
      var action_bumps, addedVal, level_bumps, message, newFame, nextLevel, oldFame, step, total_shields, total_skills, _i;
      addedVal = parseInt($(".newFame").text(), 10);
      oldFame = parseInt($(".currentFame").text(), 10);
      newFame = addedVal + oldFame;
      localStorage.mage_knight_current_fame = newFame;
      action_bumps = 0;
      level_bumps = 0;
      total_shields = 1;
      total_skills = 0;
      for (step = _i = oldFame; oldFame <= newFame ? _i < newFame : _i > newFame; step = oldFame <= newFame ? ++_i : --_i) {
        if (_(ACTION_THRESHOLDS).contains(step)) {
          action_bumps += 1;
          total_skills = ACTION_THRESHOLDS.indexOf(step) + 1;
        }
        if (_(SHIELD_THRESHOLDS).contains(step)) {
          level_bumps += 1;
          total_shields = SHIELD_THRESHOLDS.indexOf(step) + 2;
        }
      }
      message = void 0;
      if (action_bumps >= 1) {
        message = "You may now choose " + action_bumps + " new Advanced Action\n" + (plur(action_bumps, "card")) + " and " + action_bumps + " new Skill\n" + (plur(action_bumps, "token")) + ".<br/><br/>\nYou should now have a total of " + total_skills + " Skill " + (plur(total_skills, "token")) + ".";
      }
      if (level_bumps >= 1) {
        message = "You may now take " + level_bumps + " Level " + (plur(level_bumps, "token")) + " from your\nstack and flip it over, making it into a Command token.<br /><br />\nYou should now have a total of " + total_shields + "\navailable Command " + (plur(total_shields, "token")) + ".";
      }
      if ((action_bumps >= 1) && (level_bumps >= 1)) {
        message = "You may now take " + level_bumps + " Level token from your stack, " + action_bumps + " Advanced Action card and " + action_bumps + " Skill token.";
      }
      nextLevel = Math.min.apply(null, _(_(ACTION_THRESHOLDS).union(SHIELD_THRESHOLDS)).filter(function(item) {
        return item > newFame;
      }));
      if (message == null) {
        message = "You will get another benefit at Fame " + nextLevel + ".";
      }
      $(".newFame").text(0);
      $(".currentFame").text(newFame);
      $(".fame.odometer").text(newFame);
      $(".view").hide();
      $(".effectView").show();
      return $(".effect").html(message);
    });
    return $(".button.ok").click(function() {
      $(".view").hide();
      return $(".mainDisplay").show();
    });
  });

}).call(this);
